# These are supported funding model platforms
# Entre na pasta que contém o Eliaspk-BOT (o ZIP que você baixou e descompactou)
cd waba_bot          # ou o nome da sua pasta

# Inicializa o repositório Git
git init

# Adiciona todos os arquivos
git add .

# Primeiro commit
git commit -m "Versão inicial do Eliaspk-BOT"

# Conecta ao repositório remoto (substitua pela sua URL)
git remote add origin https://github.com/<seu‑user>/Eliaspk-BOT.git

# Envia (push) a branch main
git branch -M main
git push -u origin main

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
